name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ '**' ]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - "2.3"
          - "2.4"
          - "2.5"
          - "2.6"
          - "2.7"
          - "3.0"
          - "3.1"
          - "3.2"
          - "3.3"
          - "jruby-9.4"
        imagemagick: ["default"]

        include:
          - ruby: "3.3"
            imagemagick: "7.1.1"

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Update apt
        env:
          DEBIAN_FRONTEND: noninteractive
        run:
          sudo apt-get update -qq -o Acquire::Retries=3

      - name: Install ImageMagick
        env:
          DEBIAN_FRONTEND: noninteractive
        run:
          sudo apt-get install -qq -o Acquire::Retries=3 imagemagick graphicsmagick

      - name: Update ImageMagick
        if: ${{ matrix.imagemagick != 'default' }}
        run: |
          im_download_path=$(curl -sf https://download.imagemagick.org/archive/releases/ | grep -o "ImageMagick-${{ matrix.imagemagick }}-.[0-9]*.tar.xz" | tail -1)
          curl -f "https://download.imagemagick.org/archive/releases/$im_download_path" > ImageMagick.tar.xz
          tar xf ImageMagick.tar.xz
          cd ImageMagick-*
          ./configure --prefix=/usr
          sudo make install

      - name: ImageMagick version
        run: convert -version

      - name: Run tests (ImageMagick)
        run: bundle exec rspec

      - name: Run tests (GraphicsMagick)
        run: GM=1 bundle exec rspec
